const constans = {
    GET_INITIAL_DATA: 'GET_INITIAL_DATA',
    GET_INITIAL_DATA_ERROR: 'GET_INITIAL_DATA_ERROR',
    SET_INITIAL_DATA: 'SET_INITIAL_DATA',
    ADD_MOVIE: 'ADD_MOVIE',
    ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',
    EDIT_MOVIE: 'EDIT_MOVIE',
    EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',
    DELETE_MOVIE: 'DELETE_MOVIE',
    POPUP_ERROR: 'POPUP_ERROR',
    SHOW_DETAILS: 'SHOW_DETAILS',
    HIDE_DETAILS: 'HIDE_DETAILS',
    SHOW_ADD_MOVIE_POPUP: 'SHOW_ADD_MOVIE_POPUP',
    SHOW_DELETE_MOVIE_POPUP: 'SHOW_DELETE_MOVIE_POPUP',
    SHOW_EDIT_MOVIE_POPUP: 'SHOW_EDIT_MOVIE_POPUP',
    CLOSE_ADD_MOVIE_POPUP: 'CLOSE_ADD_MOVIE_POPUP',
    CLOSE_DELETE_MOVIE_POPUP: 'CLOSE_DELETE_MOVIE_POPUP',
    CLOSE_EDIT_MOVIE_POPUP: 'CLOSE_EDIT_MOVIE_POPUP',
};


export default constans;
